#!/bin/bash

agent() {
  if [ -z "$1" ]; then
    echo "Usage: agent <prompt>"
    return 1
  fi

  local prompt="$1"

  echo "$prompt"


response=$(curl -s https://api.openai.com/v1/chat/completions \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer 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" \
 -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
     {
        "role": "system",
        "content": "Return an array of sequential bash commands to achieve the functionality mentioned in the prompt.array format is commands:[]. only return the array and nothing else. only the array should be returned no other texts or anything. no whitespaces"
     },
      {
        "role": "user",
        "content": "'"$prompt"'"
      }
    ],
    "temperature": 1,
    "max_tokens": 256,
    "top_p": 1,
    "frequency_penalty": 0,
    "presence_penalty": 0
  }')
  

conten=$(echo "$response" | jq -r '.choices[0].message.content | type')
echo "$conten"


 commands=$(echo "$response" | jq -r '.choices[0].message.content | join(";")')

echo "$commands"
  echo -e "Executing commands. Please wait..\n"

 echo "$commands"




IFS=';' read -ra command_array <<< "$commands"

for command in "${command_array[@]}"; do
    echo "Executing: $command"
  #  eval "$command"
     done


  echo -e "\nCommands executed successfully."


}


agent "$1"
